version: '3'

services:
  postgres12:
    image: 10.0.0.164:5000/postgres12:goldenv0.92
    container_name: postgres12
    environment:
      TZ: America/Denver
    ports:
    - "5432:5432"
    tty: true
    stdin_open: true
    command: ["/startup.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1536M
    restart: unless-stopped
